-- ========================================================
-- ESQUEMA DE BANCO DE DADOS PARA SUPABASE (COMUNICA PWA)
-- ========================================================

-- Habilitar extensões necessárias se aplicável
create extension if not exists "uuid-ossp";

-- 1. Tabela: core_cards (Cards Essenciais unificados)
create table public.core_cards (
    id bigint generated by default as identity primary key,
    word text not null,
    style_class text not null default 'solid-orange',
    img text, -- URL de imagem estática local
    image_url text, -- URL da imagem hospedada no Storage
    audio_url text, -- URL do áudio hospedado no Storage
    "order" bigint not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabela: virtues (Categorias de Fomes e Forças)
create table public.virtues (
    id bigint generated by default as identity primary key,
    folder text not null,
    style_class text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabela: virtue_items (Cards individuais pertencentes a uma categoria de Fomes e Forças)
create table public.virtue_items (
    id bigint generated by default as identity primary key,
    virtue_id bigint references public.virtues(id) on delete cascade not null,
    word text not null,
    style_class text not null,
    img text, -- URL de imagem estática local
    image_url text, -- URL da imagem hospedada no Storage
    audio_url text, -- URL do áudio hospedado no Storage
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Tabela: exercises (Playlists de Exercícios / Vídeos)
create table public.exercises (
    id bigint generated by default as identity primary key,
    title text not null,
    items jsonb not null default '[]'::jsonb, -- Array de objetos com {word, videoUrl, styleColor, styleSize, uppercase, bold}
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- ========================================================
-- CONFIGURAÇÕES DE SEGURANÇA (RLS - Row Level Security)
-- ========================================================

-- Habilitar RLS em todas as tabelas
alter table public.core_cards enable row level security;
alter table public.virtues enable row level security;
alter table public.virtue_items enable row level security;
alter table public.exercises enable row level security;

-- Criar políticas de leitura pública (qualquer usuário pode ver os cards)
create policy "Permitir leitura pública de core_cards" on public.core_cards
    for select using (true);

create policy "Permitir leitura pública de virtues" on public.virtues
    for select using (true);

create policy "Permitir leitura pública de virtue_items" on public.virtue_items
    for select using (true);

create policy "Permitir leitura pública de exercises" on public.exercises
    for select using (true);

-- Criar políticas de modificação restrita a usuários autenticados (administradores)
create policy "Permitir modificação para admins em core_cards" on public.core_cards
    for all to authenticated using (true) with check (true);

create policy "Permitir modificação para admins em virtues" on public.virtues
    for all to authenticated using (true) with check (true);

create policy "Permitir modificação para admins em virtue_items" on public.virtue_items
    for all to authenticated using (true) with check (true);

create policy "Permitir modificação para admins em exercises" on public.exercises
    for all to authenticated using (true) with check (true);


-- ========================================================
-- DADOS INICIAIS (SEED DATA)
-- ========================================================

-- Semeando core_cards com os 12 Essenciais e as 9 Respostas Rápidas originais
insert into public.core_cards (word, style_class, "order") values
-- Essenciais
('eu', 'solid-orange', 0),
('você', 'solid-orange', 1),
('quero', 'solid-orange', 2),
('gosto', 'solid-orange', 3),
('não', 'solid-orange', 4),
('sim', 'solid-orange', 5),
('mais', 'solid-orange', 6),
('acabou', 'solid-orange', 7),
('ajudar', 'solid-orange', 8),
('comer', 'solid-orange', 9),
('beber', 'solid-orange', 10),
('ir', 'solid-orange', 11),
-- Rápidas
('oi', 'border-blue', 12),
('tchau', 'border-blue', 13),
('por favor', 'border-blue', 14),
('obrigado', 'border-blue', 15),
('desculpa', 'border-blue', 16),
('certo', 'border-green', 17),
('errado', 'border-red', 18),
('espera', 'border-yellow', 19),
('socorro', 'border-red', 20);

-- Semeando Categorias de Forças e Fomes
insert into public.virtues (id, folder, style_class) values
(1, 'Sabedoria', 'border-green'),
(2, 'Humanidade', 'border-orange'),
(3, 'Justiça', 'border-yellow'),
(4, 'Moderação', 'border-blue'),
(5, 'Coragem', 'border-red'),
(6, 'Transcendência', 'border-pink'),
(7, 'Fomes', 'border-pink');

-- Ajustar sequenciador automático de ID do virtues
select setval('public.virtues_id_seq', (select max(id) from public.virtues));

-- Semeando itens das categorias
insert into public.virtue_items (virtue_id, word, style_class, img) values
-- Sabedoria (ID 1)
(1, 'Amor ao Aprendizado', 'border-green', null),
(1, 'Criatividade', 'border-green', null),
(1, 'Critério', 'border-green', null),
(1, 'Curiosidade', 'border-green', null),
(1, 'Perspectiva', 'border-green', null),

-- Humanidade (ID 2)
(2, 'Amor', 'border-orange', null),
(2, 'Generosidade', 'border-orange', null),
(2, 'Inteligência Social', 'border-orange', null),

-- Justiça (ID 3)
(3, 'Justiça', 'border-yellow', null),
(3, 'Liderança', 'border-yellow', null),
(3, 'Trabalho em Equipe', 'border-yellow', null),

-- Moderação (ID 4)
(4, 'Autorregulação', 'border-blue', null),
(4, 'Humildade', 'border-blue', null),
(4, 'Perdão', 'border-blue', null),
(4, 'Prudência', 'border-blue', null),

-- Coragem (ID 5)
(5, 'Coragem', 'border-red', null),
(5, 'Integridade', 'border-red', null),
(5, 'Perseverança', 'border-red', null),
(5, 'Vitalidade', 'border-red', null),

-- Transcendência (ID 6)
(6, 'Apreciação da Beleza', 'border-pink', null),
(6, 'Esperança', 'border-pink', null),
(6, 'Espiritualidade', 'border-pink', null),
(6, 'Gratidão', 'border-pink', null),
(6, 'Humor', 'border-pink', null),

-- Fomes (ID 7)
(7, 'Vínculo', 'border-pink', 'img/fomes/vinculo.png'),
(7, 'Diversão', 'border-pink', 'img/fomes/diversao.png'),
(7, 'Competência', 'border-pink', 'img/fomes/competencia.png'),
(7, 'Autonomia', 'border-pink', 'img/fomes/autonomia.png'),
(7, 'Segurança', 'border-pink', 'img/fomes/seguranca.png');
